[package]
name = "shin-text"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bumpalo = { workspace = true, features = ["collections"] }

once_cell = "1.18.0"